version: '3'
services:
  backend:
    build: 
      context: ./
      dockerfile: back.dockerfile
    ports:
      - '8082:80'
    volumes:
      - '/home/student/Vadim/chat-bombyk/backend:/app'
    command: ["forever", "server.js"]
  frondend:
    build:
      context: ./
      dockerfile: front.dockerfile
    ports:
      - '8000:80'
    volumes:
      - './frontend/:/data/www'
    depends_on:
      - backend