version: '3'
services:
  mychat:
    build: .
<<<<<<< Updated upstream
    ports:
      - '8080:8081'
=======
    volumes:
      - './Backend:/var/backend'
    command:
      - npm
      - start
    ports:
      - '3000:3000'
>>>>>>> Stashed changes
