version: '3'
services:
  backend:
    build: 
      context: ./
      dockerfile: back.dockerfile
    ports:
      - '8080:8081'
  frondend:
    build:
      context: ./
      dockerfile: front.dockerfile
    ports:
      - '8000:80'
    volumes:
      - './frontend/:/data/www'